#!/usr/local/bin/node

/**
 * Module dependencies.
 */
var program = require('commander');
var fs = require('fs');
var os = require('os');
var request = require('request');
var getUrl = require('./lib/getUrl');
var exec = require('child_process').exec;
var child;

program
    .version('0.0.1')
    .option('-u, --username [username]', 'Email')
    .option('-p, --password [password]', 'Password')
    .option('-k, --keywords [keywords]', 'Keywords')
    .command('play')
    .description('Try to play a song from Jing.fm')
    .action(function(options) {
        console.log('尝试登录到 Jing.fm ...');
        getUrl(options.parent.username, options.parent.password, options.parent.keywords).then(function(url) {
            play(url);
        }, function(err) {
            console.log(err);
        });
    })
    .usage('jingfm play [options]')
    .on('--help', function() {
        console.log(' Example');
        console.log();
        console.log(' $ ./jingfm -u xvfeng -p xvfeng -k Rock');
        console.log();
    });

program.parse(process.argv);

// /**
//  * GetCommand
//  *
//  * @return {[type]}
//  */
// function getCommand () {
//     var type = os.type();
//     switch(type) {
//         case 'Darwin':
//             return 'open';
//         case 'Linux':
//             return 'xdg-open';
//         case 'Windows_NT':
//             return 'start';
//     }
//   return 'google-chrome';
// }

/**
 * Open the song in the browser
 *
 * @param  {[string]} url
 */
function play(url) {
    console.log('正在打开！');

    var r = request(url);
    child = exec('mplayer ' + url, {
        maxBuffer: 2000*1024
    }, function(error, stdout, stderr) {
        console.log('播放完毕!！');
    });
}
