#!/usr/bin/env node

/**
 * Module dependencies.
 */
var program = require('commander');
var getUrl = require('./lib/getUrl');
var exec = require('child_process').exec;
var clc = require('cli-color');
var child;

program
    .version('0.0.1')
    .option('-u, --username [username]', 'Email')
    .option('-p, --password [password]', 'Password')
    .option('-k, --keywords [keywords]', 'Keywords')
    .command('play')
    .description('Try to play a song from Jing.fm')
    .action(function(options) {
        console.log('尝试登录到 Jing.fm ...');
        getUrl(options.parent.username, options.parent.password, options.parent.keywords).then(function(urls) {
            play(urls);
        }, function(err) {
            console.log(err);
        });
    })
    .usage('jingfm play [options]')
    .on('--help', function() {
        console.log(' Example');
        console.log();
        console.log(' $ ./jingfm play -u xvfeng -p xvfeng -k Rock');
        console.log();
    });

program.parse(process.argv);

/**
 * Open the song in the browser
 *
 * @param  {[string]} url
 */
function play(urls) {
    console.log(clc.green('开始播放！'));
    child = exec('mplayer ' + urls, {
        maxBuffer: 20000*1024
    }, function(error, stdout, stderr) {
        if(error) console.log(error);
        console.log('播放完毕!！');
    });
}
